server:
  tomcat:
    max-http-form-post-size: 100MB

spring:
  datasource:
    username: root
    password: "0924"
    url: jdbc:mariadb://localhost:3306/locarie

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  issuer: locarie
  secret: lulu-locarie
  expiration: 259200  # unit: s, 30 days
