jwt:
  issuer: locarie
  secret: lulu-locarie
  expiration: 259200  # unit: s, 30 days

server:
  tomcat:
    max-http-form-post-size: 100MB

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: prod
