spring:
  datasource:
    username: root
    password: "0924"
    url: jdbc:mariadb://localhost:3306/locarie

  mail:
    host: smtp.gmail.com
    port: 587
    username: luty@locarie.com
    password: "gbqm ukpt dbsr uqzq"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update

storage:
  type: local
  url-prefix: http://localhost:8080/

validation:
  code:
    expire: 300  # unit: s
