spring:
  datasource:
    username: root
    password: "0924"
    url: jdbc:mariadb://localhost:3306/locarie

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  issuer: locarie
  secret: lulu-locarie
  expiration: 259200  # unit: s, 30 days
