server:
  port: 443
  ssl:
    key-alias: tomcat
    key-store-password: 123456
#    key-store-type: PKCS12
    key-store-type: JKS
    key-store: classpath:api.locarie.com.jks


spring:
  data:
    redis:
      host: test-ro.7mrd1j.ng.0001.euw2.cache.amazonaws.com
      port: 6379
  datasource:
    username: qiu
    password: qiuyh227515
    url: jdbc:mariadb://luludb.c9ks62mikoko.eu-west-2.rds.amazonaws.com:3306/locarie

  mail:
    host: smtp.gmail.com
    port: 587
    username: contactus@locarie.com
    password: "umog ijue lbeh rupt"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update

storage:
  type: local
  url-prefix: https://api.locarie.com/

validation:
  code:
    expire: 300  # unit: s

